server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wmc1/ten-config.git
  rabbitmq:
    host: 192.168.233.129
management:   # 暴露触发消息总线的地址
  endpoints:  #z注意  这里有s
    web:
      exposure:
        include: bus-refresh