server:
  port: 9005
spring:
  application:
    name: tensquare-gathering #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.233.129:3306/tensquare_gathering?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  redis:
    host: 192.168.233.129
